import { app, BrowserWindow, WebContentsView, ipcMain, session } from 'electron'
import { join } from 'node:path'
import { randomUUID } from 'node:crypto'
import type { BrowserTab } from '../shared/types'
import { DatabaseConnection } from './database/connection'
import { ProfileRepository } from './database/repositories/profile-repository'
import { SettingsRepository } from './database/repositories/settings-repository'
import { HistoryRepository } from './database/repositories/history-repository'
import { BookmarkRepository } from './database/repositories/bookmark-repository'
import { BookmarkFolderRepository } from './database/repositories/bookmark-folder-repository'
import { SearchEngineRepository } from './database/repositories/search-engine-repository'
import { SearchService } from './services/search/search-service'
const HOME_URL = 'grehem://newtab'
interface ManagedTab extends BrowserTab { view?: WebContentsView }
let mainWindow: BrowserWindow | null = null; let activeTabId = ''; const tabs = new Map<string, ManagedTab>(); const closedTabs: Array<{ url: string; title: string }> = []
let profileId = 0; let database: DatabaseConnection; let settingsRepository: SettingsRepository; let historyRepository: HistoryRepository; let bookmarkRepository: BookmarkRepository; let folderRepository: BookmarkFolderRepository; let searchEngineRepository: SearchEngineRepository; let searchService: SearchService
const text = (value: unknown, max: number) => typeof value === 'string' && value.trim().length > 0 && value.length <= max ? value.trim() : null
const positiveId = (value: unknown) => typeof value === 'number' && Number.isSafeInteger(value) && value > 0 ? value : null
const tabId = (value: unknown) => { if (typeof value !== 'string' || value.length === 0 || value.length > 100) throw new Error('Aba inválida'); return value }
function tab(id: string) { return tabs.get(id) }
function snapshot(value: ManagedTab): BrowserTab { return { id: value.id, title: value.title, url: value.url, favicon: value.favicon, isLoading: value.isLoading, canGoBack: value.canGoBack, canGoForward: value.canGoForward, isPinned: value.isPinned, kind: value.kind } }
function emit(channel: string, value: unknown) { mainWindow?.webContents.send(channel, value) }
function emitTab(value: ManagedTab) { emit('tab:update', snapshot(value)) }
function bounds() { if (!mainWindow) return; const [width, height] = mainWindow.getContentSize(); tab(activeTabId)?.view?.setBounds({ x: 0, y: 112, width, height: Math.max(0, height - 112) }) }
function detach(value: ManagedTab) { if (value.view && mainWindow) mainWindow.contentView.removeChildView(value.view) }
function attach(value: ManagedTab) { if (mainWindow && value.view) { mainWindow.contentView.addChildView(value.view); bounds() } }
function wire(value: ManagedTab) { const wc = value.view!.webContents; wc.on('did-start-loading', () => { value.isLoading = true; emitTab(value) }); wc.on('did-stop-loading', () => { value.isLoading = false; value.canGoBack = wc.canGoBack(); value.canGoForward = wc.canGoForward(); emitTab(value) }); wc.on('page-title-updated', (_e, title) => { value.title = title || 'Nova aba'; emitTab(value) }); wc.on('page-favicon-updated', (_e, icons) => { value.favicon = icons[0]; emitTab(value) }); wc.on('did-navigate', (_e, url) => { value.url = url; value.kind = 'web'; value.canGoBack = wc.canGoBack(); value.canGoForward = wc.canGoForward(); if (!url.startsWith('grehem://')) historyRepository.add(profileId, url, value.title, value.favicon ?? null); emitTab(value) }); wc.on('did-navigate-in-page', (_e, url) => { value.url = url; emitTab(value) }) }
function viewFor(value: ManagedTab) { if (!value.view) { value.view = new WebContentsView({ webPreferences: { sandbox: true, contextIsolation: true, nodeIntegration: false, partition: 'persist:profile-default' } }); wire(value) } return value.view }
async function createTab(url = HOME_URL): Promise<BrowserTab> { const home = url.startsWith('grehem://'); const value: ManagedTab = { id: randomUUID(), title: home ? 'Nova aba' : 'Carregando…', url, isLoading: !home, canGoBack: false, canGoForward: false, isPinned: false, kind: home ? 'newtab' : 'web' }; if (!home) await viewFor(value).webContents.loadURL(url); tabs.set(value.id, value); await activate(value.id); return snapshot(value) }
async function activate(id: string) { const next = tab(id); if (!next || !mainWindow) return; const previous = tab(activeTabId); if (previous && previous.id !== id) detach(previous); activeTabId = id; if (next.view) attach(next); emit('tab:active', id); emitTab(next) }
async function navigate(id: string, input: string) { const value = tab(id); const query = text(input, 2048); if (!value || !query) throw new Error('Entrada inválida'); const url = searchService.resolve(query); if (url.startsWith('grehem://')) { if (value.view) { value.view.webContents.close(); value.view = undefined }; value.url = url; value.title = 'Nova aba'; value.kind = 'newtab'; value.isLoading = false; emitTab(value); return } const view = viewFor(value); value.kind = 'web'; value.url = url; value.isLoading = true; if (value.id === activeTabId) attach(value); emitTab(value); await view.webContents.loadURL(url) }
async function closeTab(id: string) { const value = tab(id); if (!value) return false; closedTabs.push({ url: value.url, title: value.title }); if (closedTabs.length > 20) closedTabs.shift(); detach(value); value.view?.webContents.close(); tabs.delete(id); if (!tabs.size) await createTab(); else if (activeTabId === id) await activate(Array.from(tabs.keys())[0]); emit('tabs:list', Array.from(tabs.values()).map(snapshot)); return true }
function registerIpc() {
  ipcMain.handle('tabs:list', () => Array.from(tabs.values()).map(snapshot)); ipcMain.handle('tabs:create', (_e, url?: unknown) => createTab(url === undefined ? HOME_URL : text(url, 2048) ?? HOME_URL)); ipcMain.handle('tabs:close', (_e, id: unknown) => closeTab(tabId(id))); ipcMain.handle('tabs:activate', (_e, id: unknown) => activate(tabId(id))); ipcMain.handle('tabs:navigate', (_e, id: unknown, input: unknown) => navigate(tabId(id), typeof input === 'string' ? input : '')); ipcMain.handle('tabs:back', (_e, id: unknown) => tab(tabId(id))?.view?.webContents.goBack()); ipcMain.handle('tabs:forward', (_e, id: unknown) => tab(tabId(id))?.view?.webContents.goForward()); ipcMain.handle('tabs:reload', (_e, id: unknown) => tab(tabId(id))?.view?.webContents.reload()); ipcMain.handle('tabs:stop', (_e, id: unknown) => tab(tabId(id))?.view?.webContents.stop()); ipcMain.handle('tabs:reopen', () => { const item = closedTabs.pop(); return item ? createTab(item.url) : null })
  ipcMain.handle('settings:list', () => settingsRepository.list(profileId)); ipcMain.handle('settings:set', (_e, key: unknown, value: unknown) => { const k = text(key, 100); const v = text(value, 1000); if (!k || !v) throw new Error('Configuração inválida'); settingsRepository.set(profileId, k, v) })
  ipcMain.handle('history:list', (_e, query?: unknown) => historyRepository.list(profileId, query === undefined ? '' : (text(query, 200) ?? ''))); ipcMain.handle('history:delete', (_e, id: unknown) => { const value = positiveId(id); if (!value) throw new Error('Histórico inválido'); historyRepository.delete(profileId, value) }); ipcMain.handle('history:clear', () => historyRepository.clear(profileId))
  ipcMain.handle('bookmarks:list', (_e, query?: unknown) => bookmarkRepository.list(profileId, query === undefined ? '' : (text(query, 200) ?? ''))); ipcMain.handle('bookmarks:create', (_e, title: unknown, url: unknown, folderId?: unknown) => { const t = text(title, 500); const u = text(url, 2048); const f = folderId === undefined || folderId === null ? null : positiveId(folderId); if (!t || !u || (folderId !== undefined && folderId !== null && !f)) throw new Error('Favorito inválido'); return bookmarkRepository.create(profileId, t, u, f) }); ipcMain.handle('bookmarks:delete', (_e, id: unknown) => { const value = positiveId(id); if (!value) throw new Error('Favorito inválido'); bookmarkRepository.delete(profileId, value) })
  ipcMain.handle('bookmark-folders:list', () => folderRepository.list(profileId)); ipcMain.handle('bookmark-folders:create', (_e, name: unknown, parentId?: unknown) => { const n = text(name, 200); const p = parentId === undefined || parentId === null ? null : positiveId(parentId); if (!n || (parentId !== undefined && parentId !== null && !p)) throw new Error('Pasta inválida'); return folderRepository.create(profileId, n, p) })
  ipcMain.handle('search-engines:list', () => searchEngineRepository.list(profileId)); ipcMain.handle('search-engines:set-default', (_e, id: unknown) => { const value = positiveId(id); if (!value) throw new Error('Mecanismo inválido'); searchEngineRepository.setDefault(profileId, value) }); ipcMain.handle('search-engines:create', (_e, name: unknown, keyword: unknown, url: unknown) => { const n = text(name, 100); const k = text(keyword, 50); const u = text(url, 2048); if (!n || !k || !u) throw new Error('Mecanismo inválido'); return searchEngineRepository.create(profileId, n, u, k) })
}
function initializeData() { database = new DatabaseConnection(join(app.getPath('userData'), 'grehem.sqlite')); database.migrate(); const profile = new ProfileRepository(database.db).getDefault(); profileId = profile.id; settingsRepository = new SettingsRepository(database.db); settingsRepository.seed(profileId, { language: 'pt-BR', theme: 'light', zoom: '100', searchEngine: 'Google', homePage: HOME_URL }); searchEngineRepository = new SearchEngineRepository(database.db); if (!searchEngineRepository.list(profileId).length) { searchEngineRepository.create(profileId, 'Google', 'https://www.google.com/search?q=%s', 'google', true, true); searchEngineRepository.create(profileId, 'Bing', 'https://www.bing.com/search?q=%s', 'bing', true); searchEngineRepository.create(profileId, 'DuckDuckGo', 'https://duckduckgo.com/?q=%s', 'ddg', true) }; searchService = new SearchService(searchEngineRepository, profileId); historyRepository = new HistoryRepository(database.db); bookmarkRepository = new BookmarkRepository(database.db); folderRepository = new BookmarkFolderRepository(database.db) }
async function createWindow() { mainWindow = new BrowserWindow({ width: 1366, height: 820, minWidth: 900, minHeight: 600, backgroundColor: '#f7f8fa', title: 'Grehem Browser', webPreferences: { preload: join(__dirname, '../preload/index.mjs'), contextIsolation: true, sandbox: true, nodeIntegration: false } }); mainWindow.on('resize', bounds); mainWindow.on('closed', () => { mainWindow = null }); await mainWindow.loadURL(process.env.ELECTRON_RENDERER_URL || `file://${join(__dirname, '../renderer/index.html')}`); await createTab() }
app.whenReady().then(() => { initializeData(); registerIpc(); session.defaultSession.setPermissionRequestHandler((_c, _p, callback) => callback(false)); void createWindow(); app.on('activate', () => { if (!BrowserWindow.getAllWindows().length) void createWindow() }) }); app.on('before-quit', () => database?.close()); app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit() })
