import { app, BrowserWindow, WebContentsView, ipcMain, session } from 'electron'
import { join } from 'node:path'
import { randomUUID } from 'node:crypto'
import type { BrowserTab } from '../shared/types'
import { DatabaseConnection } from './database/connection'
import { ProfileRepository } from './database/repositories/profile-repository'
import { SettingsRepository } from './database/repositories/settings-repository'
import { HistoryRepository } from './database/repositories/history-repository'
import { BookmarkRepository } from './database/repositories/bookmark-repository'
import { BookmarkFolderRepository } from './database/repositories/bookmark-folder-repository'
import { SearchEngineRepository } from './database/repositories/search-engine-repository'
import { SearchService } from './services/search/search-service'

const HOME_URL = 'grehem://newtab'
interface ManagedTab extends BrowserTab { view?: WebContentsView; pendingVisit?: boolean }
let mainWindow: BrowserWindow | null = null
let activeTabId = ''
const tabs = new Map<string, ManagedTab>()
const closedTabs: Array<{ url: string; title: string }> = []
let profileId = 0
let database: DatabaseConnection
let settingsRepository: SettingsRepository
let historyRepository: HistoryRepository
let bookmarkRepository: BookmarkRepository
let folderRepository: BookmarkFolderRepository
let searchEngineRepository: SearchEngineRepository
let searchService: SearchService
const text = (value: unknown, max: number): string | null => typeof value === 'string' && value.trim().length > 0 && value.length <= max ? value.trim() : null
const positiveId = (value: unknown): number | null => typeof value === 'number' && Number.isSafeInteger(value) && value > 0 ? value : null
const validTabId = (value: unknown): string => { if (typeof value !== 'string' || value.length === 0 || value.length > 100) throw new Error('Aba inválida'); return value }
function getTab(id: string) { return tabs.get(id) }
function snapshot(tab: ManagedTab): BrowserTab { return { id: tab.id, title: tab.title, url: tab.url, favicon: tab.favicon, isLoading: tab.isLoading, canGoBack: tab.canGoBack, canGoForward: tab.canGoForward, isPinned: tab.isPinned, kind: tab.kind } }
function emit(channel: string, value: unknown) { mainWindow?.webContents.send(channel, value) }
function emitTab(tab: ManagedTab) { emit('tab:update', snapshot(tab)) }
function applyZoom(tab: ManagedTab) { const raw = Number(settingsRepository.get(profileId, 'zoom') ?? '100'); const percent = Number.isFinite(raw) ? Math.min(200, Math.max(25, raw)) : 100; tab.view?.webContents.setZoomFactor(percent / 100) }
function setBounds() { if (!mainWindow) return; const [width, height] = mainWindow.getContentSize(); getTab(activeTabId)?.view?.setBounds({ x: 0, y: 112, width, height: Math.max(0, height - 112) }) }
function detach(tab: ManagedTab) { if (tab.view && mainWindow) mainWindow.contentView.removeChildView(tab.view) }
function attach(tab: ManagedTab) { if (mainWindow && tab.view) { mainWindow.contentView.addChildView(tab.view); applyZoom(tab); setBounds() } }
function recordCompletedVisit(tab: ManagedTab) { if (!tab.pendingVisit || tab.url.startsWith('grehem://')) return; const title = tab.title === 'Carregando…' ? '' : tab.title; historyRepository.add(profileId, tab.url, title, tab.favicon ?? null); tab.pendingVisit = false }
function wireView(tab: ManagedTab) { const wc = tab.view!.webContents; wc.on('did-start-loading', () => { tab.isLoading = true; emitTab(tab) }); wc.on('did-stop-loading', () => { tab.isLoading = false; tab.canGoBack = wc.canGoBack(); tab.canGoForward = wc.canGoForward(); recordCompletedVisit(tab); emitTab(tab) }); wc.on('page-title-updated', (_event, title) => { tab.title = title || 'Nova aba'; emitTab(tab) }); wc.on('page-favicon-updated', (_event, favicons) => { tab.favicon = favicons[0]; emitTab(tab) }); wc.on('did-navigate', (_event, url) => { tab.url = url; tab.kind = 'web'; tab.pendingVisit = !url.startsWith('grehem://'); tab.canGoBack = wc.canGoBack(); tab.canGoForward = wc.canGoForward(); emitTab(tab) }); wc.on('did-navigate-in-page', (_event, url) => { tab.url = url; emitTab(tab) }); wc.on('did-fail-load', (_event, errorCode, _description, validatedURL, isMainFrame) => { if (isMainFrame && errorCode !== -3) { tab.isLoading = false; tab.pendingVisit = false; tab.title = 'Falha ao carregar'; tab.url = validatedURL; emitTab(tab) } }) }
function viewFor(tab: ManagedTab): WebContentsView { if (!tab.view) { tab.view = new WebContentsView({ webPreferences: { sandbox: true, contextIsolation: true, nodeIntegration: false, partition: `persist:profile-${profileId}` } }); wireView(tab); applyZoom(tab) } return tab.view }
async function createTab(url = HOME_URL): Promise<BrowserTab> { const home = url.startsWith('grehem://'); const tab: ManagedTab = { id: randomUUID(), title: home ? 'Nova aba' : 'Carregando…', url, isLoading: !home, canGoBack: false, canGoForward: false, isPinned: false, kind: home ? 'newtab' : 'web', pendingVisit: !home }; if (!home) await viewFor(tab).webContents.loadURL(url); tabs.set(tab.id, tab); await activateTab(tab.id); return snapshot(tab) }
async function activateTab(id: string) { const next = getTab(id); if (!next || !mainWindow) return; const previous = getTab(activeTabId); if (previous && previous.id !== id) detach(previous); activeTabId = id; if (next.view) attach(next); emit('tab:active', id); emitTab(next) }
async function navigate(id: string, input: string) { const tab = getTab(id); const value = text(input, 2048); if (!tab || value === null) throw new Error('Entrada inválida'); const url = searchService.resolve(value); if (url.startsWith('grehem://')) { if (tab.view) { tab.view.webContents.close(); tab.view = undefined }; tab.url = url; tab.title = 'Nova aba'; tab.kind = 'newtab'; tab.isLoading = false; tab.pendingVisit = false; emitTab(tab); return } const view = viewFor(tab); tab.kind = 'web'; tab.url = url; tab.isLoading = true; tab.pendingVisit = true; if (tab.id === activeTabId) attach(tab); emitTab(tab); await view.webContents.loadURL(url) }
async function closeTab(id: string) { const tab = getTab(id); if (!tab) return false; closedTabs.push({ url: tab.url, title: tab.title }); if (closedTabs.length > 20) closedTabs.shift(); detach(tab); tab.view?.webContents.close(); tabs.delete(id); if (!tabs.size) await createTab(); else if (activeTabId === id) await activateTab(Array.from(tabs.keys())[0]); emit('tabs:list', Array.from(tabs.values()).map(snapshot)); return true }
function registerIpc() {
  ipcMain.handle('tabs:list', () => Array.from(tabs.values()).map(snapshot)); ipcMain.handle('tabs:create', (_event, url?: unknown) => createTab(url === undefined ? HOME_URL : text(url, 2048) ?? HOME_URL)); ipcMain.handle('tabs:close', (_event, id: unknown) => closeTab(validTabId(id))); ipcMain.handle('tabs:activate', (_event, id: unknown) => activateTab(validTabId(id))); ipcMain.handle('tabs:navigate', (_event, id: unknown, input: unknown) => navigate(validTabId(id), typeof input === 'string' ? input : '')); ipcMain.handle('tabs:back', (_event, id: unknown) => getTab(validTabId(id))?.view?.webContents.goBack()); ipcMain.handle('tabs:forward', (_event, id: unknown) => getTab(validTabId(id))?.view?.webContents.goForward()); ipcMain.handle('tabs:reload', (_event, id: unknown) => getTab(validTabId(id))?.view?.webContents.reload()); ipcMain.handle('tabs:stop', (_event, id: unknown) => getTab(validTabId(id))?.view?.webContents.stop()); ipcMain.handle('tabs:reopen', () => { const item = closedTabs.pop(); return item ? createTab(item.url) : null })
  ipcMain.handle('settings:list', () => settingsRepository.list(profileId)); ipcMain.handle('settings:set', (_event, key: unknown, value: unknown) => { const validKey = text(key, 100); const validValue = text(value, 1000); if (!validKey || validValue === null) throw new Error('Configuração inválida'); settingsRepository.set(profileId, validKey, validValue); if (validKey === 'zoom') { const percent = Number(validValue); if (!Number.isFinite(percent) || percent < 25 || percent > 200) throw new Error('Zoom inválido'); tabs.forEach(applyZoom) } })
  ipcMain.handle('history:list', (_event, query?: unknown) => historyRepository.list(profileId, query === undefined ? '' : text(query, 200) ?? '')); ipcMain.handle('history:delete', (_event, historyId: unknown) => { const id = positiveId(historyId); if (!id) throw new Error('Histórico inválido'); historyRepository.delete(profileId, id) }); ipcMain.handle('history:clear', () => historyRepository.clear(profileId))
  ipcMain.handle('bookmarks:list', (_event, query?: unknown) => bookmarkRepository.list(profileId, query === undefined ? '' : text(query, 200) ?? '')); ipcMain.handle('bookmarks:find-by-url', (_event, url: unknown) => { const value = text(url, 2048); if (!value) throw new Error('URL inválida'); return bookmarkRepository.findByUrl(profileId, value) ?? null }); ipcMain.handle('bookmarks:create', (_event, title: unknown, url: unknown, folderId?: unknown) => { const validTitle = text(title, 500); const validUrl = text(url, 2048); const folder = folderId === undefined || folderId === null ? null : positiveId(folderId); if (!validTitle || !validUrl || (folderId !== undefined && folderId !== null && !folder) || (folder !== null && !folderRepository.belongsToProfile(profileId, folder))) throw new Error('Favorito inválido'); return bookmarkRepository.create(profileId, validTitle, validUrl, folder) }); ipcMain.handle('bookmarks:delete', (_event, bookmarkId: unknown) => { const id = positiveId(bookmarkId); if (!id) throw new Error('Favorito inválido'); bookmarkRepository.delete(profileId, id) })
  ipcMain.handle('bookmark-folders:list', () => folderRepository.list(profileId)); ipcMain.handle('bookmark-folders:create', (_event, name: unknown, parentId?: unknown) => { const validName = text(name, 200); const parent = parentId === undefined || parentId === null ? null : positiveId(parentId); if (!validName || (parentId !== undefined && parentId !== null && !parent)) throw new Error('Pasta inválida'); return folderRepository.create(profileId, validName, parent) })
  ipcMain.handle('search-engines:list', () => searchEngineRepository.list(profileId)); ipcMain.handle('search-engines:set-default', (_event, engineId: unknown) => { const id = positiveId(engineId); if (!id) throw new Error('Mecanismo inválido'); const engine = searchEngineRepository.setDefault(profileId, id); settingsRepository.set(profileId, 'searchEngine', engine.keyword) }); ipcMain.handle('search-engines:create', (_event, name: unknown, keyword: unknown, searchUrl: unknown) => { const validName = text(name, 100); const validKeyword = text(keyword, 50); const validUrl = text(searchUrl, 2048); if (!validName || !validKeyword || !validUrl) throw new Error('Mecanismo inválido'); return searchEngineRepository.create(profileId, validName, validUrl, validKeyword) })
}
function initializeData() { database = new DatabaseConnection(join(app.getPath('userData'), 'grehem.sqlite')); database.migrate(); const profile = new ProfileRepository(database.db).getDefault(); profileId = profile.id; settingsRepository = new SettingsRepository(database.db); settingsRepository.seed(profileId, { language: 'pt-BR', theme: 'light', zoom: '100', searchEngine: 'google', homePage: HOME_URL }); searchEngineRepository = new SearchEngineRepository(database.db); if (!searchEngineRepository.list(profileId).length) { searchEngineRepository.create(profileId, 'Google', 'https://www.google.com/search?q=%s', 'google', true, true); searchEngineRepository.create(profileId, 'Bing', 'https://www.bing.com/search?q=%s', 'bing', true); searchEngineRepository.create(profileId, 'DuckDuckGo', 'https://duckduckgo.com/?q=%s', 'ddg', true) }; searchService = new SearchService(searchEngineRepository, profileId); historyRepository = new HistoryRepository(database.db); bookmarkRepository = new BookmarkRepository(database.db); folderRepository = new BookmarkFolderRepository(database.db) }
async function createWindow() { mainWindow = new BrowserWindow({ width: 1366, height: 820, minWidth: 900, minHeight: 600, backgroundColor: '#f7f8fa', title: 'Grehem Browser', webPreferences: { preload: join(__dirname, '../preload/index.mjs'), contextIsolation: true, sandbox: true, nodeIntegration: false } }); mainWindow.on('resize', setBounds); mainWindow.on('closed', () => { mainWindow = null }); await mainWindow.loadURL(process.env.ELECTRON_RENDERER_URL || `file://${join(__dirname, '../renderer/index.html')}`); await createTab() }
app.whenReady().then(() => { initializeData(); registerIpc(); session.defaultSession.setPermissionRequestHandler((_contents, _permission, callback) => callback(false)); void createWindow(); app.on('activate', () => { if (!BrowserWindow.getAllWindows().length) void createWindow() }) }); app.on('before-quit', () => database?.close()); app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit() })
