import { describe, expect, it } from 'vitest'
import { DatabaseConnection } from './connection'
import { ProfileRepository } from './repositories/profile-repository'
import { HistoryRepository } from './repositories/history-repository'
import { BookmarkRepository } from './repositories/bookmark-repository'
import { BookmarkFolderRepository } from './repositories/bookmark-folder-repository'
import { SearchEngineRepository } from './repositories/search-engine-repository'
describe('Phase 2B blockers and high priority fixes', () => {
  it('deduplicates history, preserves useful title data, and rejects internal URLs', () => { const db = new DatabaseConnection(':memory:'); db.migrate(); const profile = new ProfileRepository(db.db).getDefault(); const history = new HistoryRepository(db.db); history.add(profile.id, 'https://example.test', 'Carregando…'); history.add(profile.id, 'https://example.test', 'Example'); expect(history.list(profile.id)).toHaveLength(1); expect(history.list(profile.id)[0].title).toBe('Example'); expect(() => history.add(profile.id, 'grehem://newtab')).toThrow(); db.close() })
  it('finds bookmarks by profile and rejects duplicates', () => { const db = new DatabaseConnection(':memory:'); db.migrate(); const profiles = new ProfileRepository(db.db); const one = profiles.getDefault(); const two = profiles.create('Other'); const bookmarks = new BookmarkRepository(db.db); const item = bookmarks.create(one.id, 'Example', 'https://example.test'); expect(bookmarks.findByUrl(one.id, 'https://example.test')?.id).toBe(item.id); expect(bookmarks.findByUrl(two.id, 'https://example.test')).toBeUndefined(); expect(() => bookmarks.create(one.id, 'Another', 'https://example.test')).toThrow(/exists/); db.close() })
  it('rejects foreign folders and prevents removal of the default engine', () => { const db = new DatabaseConnection(':memory:'); db.migrate(); const profiles = new ProfileRepository(db.db); const one = profiles.getDefault(); const two = profiles.create('Other'); const folders = new BookmarkFolderRepository(db.db); const foreignFolder = folders.create(two.id, 'Other folder'); expect(folders.belongsToProfile(one.id, foreignFolder.id)).toBe(false); const engines = new SearchEngineRepository(db.db); const defaultEngine = engines.create(one.id, 'Google', 'https://google.test?q=%s', 'google', true, true); expect(() => engines.delete(one.id, defaultEngine.id)).toThrow(/default/); expect(engines.getDefault(one.id)?.id).toBe(defaultEngine.id); const custom = engines.create(one.id, 'Custom', 'https://custom.test?q=%s', 'custom'); engines.delete(one.id, custom.id); expect(engines.find(one.id, custom.id)).toBeUndefined(); expect(() => engines.setDefault(one.id, engines.create(two.id, 'Other', 'https://other.test?q=%s', 'other', false, true).id)).toThrow(/profile/); db.close() })
})
