import { describe, expect, it } from 'vitest'
import { DatabaseConnection } from './connection'
import { ProfileRepository } from './repositories/profile-repository'
import { HistoryRepository } from './repositories/history-repository'
import { BookmarkRepository } from './repositories/bookmark-repository'
import { BookmarkFolderRepository } from './repositories/bookmark-folder-repository'
import { SearchEngineRepository } from './repositories/search-engine-repository'
describe('Phase 2B hardening', () => {
  it('deduplicates consecutive history and rejects internal URLs', () => { const db = new DatabaseConnection(':memory:'); db.migrate(); const profile = new ProfileRepository(db.db).getDefault(); const history = new HistoryRepository(db.db); history.add(profile.id, 'https://example.test', 'Example'); history.add(profile.id, 'https://example.test', 'Example updated'); expect(history.list(profile.id)).toHaveLength(1); expect(() => history.add(profile.id, 'grehem://newtab')).toThrow(); db.close() })
  it('finds bookmarks by profile and rejects duplicates', () => { const db = new DatabaseConnection(':memory:'); db.migrate(); const profiles = new ProfileRepository(db.db); const one = profiles.getDefault(); const two = profiles.create('Other'); const bookmarks = new BookmarkRepository(db.db); const item = bookmarks.create(one.id, 'Example', 'https://example.test'); expect(bookmarks.findByUrl(one.id, 'https://example.test')?.id).toBe(item.id); expect(bookmarks.findByUrl(two.id, 'https://example.test')).toBeUndefined(); expect(() => bookmarks.create(one.id, 'Another', 'https://example.test')).toThrow(/exists/); expect(() => bookmarks.create(one.id, '  ', 'https://empty.test')).toThrow(/title/); db.close() })
  it('requires folders and engines to belong to the active profile', () => { const db = new DatabaseConnection(':memory:'); db.migrate(); const profiles = new ProfileRepository(db.db); const one = profiles.getDefault(); const two = profiles.create('Other'); const folders = new BookmarkFolderRepository(db.db); const foreignFolder = folders.create(two.id, 'Other folder'); expect(folders.belongsToProfile(one.id, foreignFolder.id)).toBe(false); const engines = new SearchEngineRepository(db.db); const foreignEngine = engines.create(two.id, 'Other', 'https://other.test?q=%s', 'other', false, true); expect(() => engines.setDefault(one.id, foreignEngine.id)).toThrow(/profile/); db.close() })
})
